### ISSUE TITLE
Module import issue after installing conda

### ISSUE THREAD

**Issue by SuperSecureHuman** [Haptein/powerplan#10] opened 2021-12-28 14:39 UTC
**Description**
I installed powerplan from AUR. After I set conda on my system, powerplan install was broken

![image](https://user-images.githubusercontent.com/88489071/147577171-eec7cdbd-5151-46f9-9db4-0d2f2f20615a.png)

It did work before I installed conda

Thanks!

**Comment by Haptein** [comment] 2021-12-29 01:47
Hmm, could you please share a link to the powerplan AUR page? I wasn't aware there was one, I also couldn't find it 😅

By default powerplan tries to use /usr/bin/python3 to run, which is the system's python install (rather than conda's).  So powerplan would require psutil to be installed systemwide. What is a bit puzzling is that it worked before conda. Did you uninstall your system's psutil? I think the output of /usr/bin/python3 could hint the cause of the problem.

**Comment by SuperSecureHuman** [comment] 2021-12-29 02:11
Oh sh*t
Really sorry, it was not AUR.

And nope I did not remove psutil from my system

Now i tried this
Deactivate conda first
pip install psutil (as sudo, because powerplan runs as root)
reopen terminal, and all good to go


If u install a module with sudo while in conda, it dosent actually install it for the root user for some reason (or I might be wrong)

**Comment by Haptein** [comment] 2021-12-29 03:17
Installing python-psutil with pacman should also work if you prefer that route :+1:

> If u install a module with sudo while in conda, it dosent actually install it for the root user for some reason (or I might be wrong)

Conda is normally installed somewhere under the user's home directory with user access in mind. Installing conda packages with sudo is normally discouraged because it would write to the same user's conda directory but with root permissions (if the conda command is found). It might be different for system wide conda installations but I personally don't see the benefit to installing conda like that.

In this case installing psutil with conda wouldn't work because the python executable being used is the one provided by your system, not the conda one. I've thought enabling the use of /usr/bin/env python3 which could work with conda installs but that also brings it's own small set of problems. I've been slowly replacing psutil functions with more performant ones, in the future powerplan won't depend on psutil at all.

**Comment by Haptein** [comment] 2021-12-31 05:22
I'm closing this issue since it looks like it was just a missing library, but feel free to comment here if there's any question/feedback.

**Closed as completed** 2021-12-31 05:23 UTC
